// Generated by scripts/sync-chat-app-model.mjs.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataFeedAcquisitionError = void 0;
exports.validateFeedAcquisitionDefinition = validateFeedAcquisitionDefinition;
exports.validateFeedAcquisitionInputs = validateFeedAcquisitionInputs;
exports.validateFeedAcquisitionOutput = validateFeedAcquisitionOutput;
const data_feed_types_cjs_1 = require("./data-feed-types.cjs");
class DataFeedAcquisitionError extends Error {
    constructor(code, message, status = 422) {
        super(message);
        this.code = code;
        this.status = status;
    }
}
exports.DataFeedAcquisitionError = DataFeedAcquisitionError;
const object = (v) => v && typeof v === 'object' && !Array.isArray(v) ? v : {};
const fail = (code, message, status = 422) => { throw new DataFeedAcquisitionError(code, message, status); };
const field = (v) => typeof v === 'string' && /^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(v) && !['constructor', 'prototype', '__proto__'].includes(v);
const pointer = (v) => typeof v === 'string' && v.length <= 500 && (v === '' || v.startsWith('/')) && !/~(?![01])/u.test(v) && !v.split('/').some(k => ['constructor', 'prototype', '__proto__'].includes(k.replace(/~1/g, '/').replace(/~0/g, '~')));
const keys = (v, allowed) => { if (Object.keys(v).some(k => !allowed.includes(k)))
    fail('INVALID_ACQUISITION', 'Acquisition contains an unsupported field.'); };
function declaredInput(d, key) { return field(key) && Object.prototype.hasOwnProperty.call(object(object(d.inputSchema).properties), key); }
function read(value, path) {
    if (!pointer(path))
        fail('INVALID_OBSERVATION_PATH', 'Use safe JSON pointers.');
    if (!path)
        return value;
    return path.slice(1).split('/').reduce((parent, key) => { key = key.replace(/~1/g, '/').replace(/~0/g, '~'); return parent && typeof parent === 'object' && Object.prototype.hasOwnProperty.call(parent, key) ? parent[key] : undefined; }, value);
}
function validateFeedAcquisitionDefinition(d) {
    if (d.type !== undefined && !data_feed_types_cjs_1.DATA_FEED_TYPES.includes(d.type))
        fail('INVALID_FEED_TYPE', 'Choose Email, File, Transaction, Calendar, Message, Portal or Source.');
    if (d.type === 'source' && (d.outputKind !== 'sources' || d.ontology?.entityType !== 'Source'))
        fail('INVALID_SOURCE_TYPE', 'Source feeds return sources and reference the Persona Source entity.');
    if (d.outputKind === 'sources' && d.type !== undefined && d.type !== 'source')
        fail('INVALID_SOURCE_TYPE', 'A Sources output uses the Source feed type.');
    if (d.acquisition === undefined)
        return;
    if (!d.type)
        fail('FEED_TYPE_REQUIRED', 'Choose a feed type before configuring acquisition.');
    const a = object(d.acquisition);
    keys(a, ['mode', 'instruction', 'policy', 'checkpoint', 'observations']);
    if (!data_feed_types_cjs_1.DATA_FEED_ACQUISITION_MODES.includes(a.mode))
        fail('INVALID_ACQUISITION_MODE', 'Choose a supported acquisition mode.');
    if (a.instruction !== undefined && (typeof a.instruction !== 'string' || !a.instruction.trim() || a.instruction.length > 4000))
        fail('INVALID_ACQUISITION', 'Instructions must be nonempty and at most 4000 characters.');
    if (a.policy !== undefined) {
        const p = object(a.policy);
        if (!a.policy || Array.isArray(a.policy) || typeof a.policy !== 'object')
            fail('INVALID_ACQUISITION_POLICY', 'Use an acquisition policy object.');
        keys(p, ['allowUserRequest', 'allowDeviceCapture', 'requestPrompt', 'observationInput']);
        for (const key of ['allowUserRequest', 'allowDeviceCapture'])
            if (p[key] !== undefined && typeof p[key] !== 'boolean')
                fail('INVALID_ACQUISITION_POLICY', 'Acquisition permissions are booleans.');
        if (p.requestPrompt !== undefined && (typeof p.requestPrompt !== 'string' || !p.requestPrompt.trim() || p.requestPrompt.length > 2000))
            fail('INVALID_ACQUISITION_POLICY', 'Use a nonempty request prompt of at most 2000 characters.');
        if (p.observationInput !== undefined && !declaredInput(d, p.observationInput))
            fail('INVALID_OBSERVATION_INPUT', 'The observation input must reference a declared input schema property.');
        if (p.allowDeviceCapture === true && d.type !== 'file')
            fail('INVALID_DEVICE_CAPTURE', 'Device capture produces File observations.');
    }
    if (['user_solicited', 'device_captured'].includes(a.mode)) {
        const p = object(a.policy);
        if (a.mode === 'user_solicited' && (p.allowUserRequest !== true || !p.requestPrompt))
            fail('USER_REQUEST_NOT_ALLOWED', 'Request-input mode requires an explicit policy and request prompt.');
        if (a.mode === 'device_captured' && (d.type !== 'file' || p.allowDeviceCapture !== true))
            fail('DEVICE_CAPTURE_NOT_ALLOWED', 'Device capture requires a File feed and explicit acquisition policy.');
        if (!declaredInput(d, p.observationInput) || !Array.isArray(object(d.inputSchema).required) || !object(d.inputSchema).required.includes(p.observationInput))
            fail('OBSERVATION_INPUT_REQUIRED', 'Active acquisition requires a declared required observation input from the playbook.');
    }
    if (a.checkpoint !== undefined) {
        const c = object(a.checkpoint);
        keys(c, ['inputParameter', 'outputPath']);
        if (!declaredInput(d, c.inputParameter) || !pointer(c.outputPath))
            fail('INVALID_CHECKPOINT', 'A checkpoint references a declared input parameter and safe output JSON pointer.');
    }
    if (a.observations !== undefined) {
        const o = object(a.observations);
        keys(o, ['recordsPath', 'identityPath', 'observedAtPath', 'provenancePath']);
        if (!pointer(o.recordsPath) || ['identityPath', 'observedAtPath', 'provenancePath'].some(key => o[key] !== undefined && !pointer(o[key])))
            fail('INVALID_OBSERVATION_PATH', 'Observation fields use safe JSON pointers.');
    }
}
function validateFeedAcquisitionInputs(d, inputs) {
    const a = d.acquisition;
    if (!a || !['user_solicited', 'device_captured'].includes(a.mode))
        return;
    const value = inputs[a.policy.observationInput];
    if (value === undefined || value === null || typeof value === 'string' && !value.trim() || Array.isArray(value) && !value.length || typeof value === 'object' && !Array.isArray(value) && !Object.keys(value).length)
        fail('OBSERVATION_REQUIRED', 'The playbook must collect the requested observation before invoking this feed.');
}
/** Validate lifecycle hints without wrapping output, storing a cursor or mutating instances. */
function validateFeedAcquisitionOutput(d, output) {
    const a = d.acquisition;
    if (!a)
        return;
    if (a.checkpoint && read(output, a.checkpoint.outputPath) === undefined)
        fail('CHECKPOINT_OUTPUT_MISSING', 'Feed output must include its declared checkpoint (JSON null marks the end).', 502);
    const o = a.observations;
    if (!o)
        return;
    const selected = read(output, o.recordsPath);
    if (selected === undefined || selected === null)
        fail('OBSERVATIONS_MISSING', 'Feed output must include its declared observations.', 502);
    const rows = Array.isArray(selected) ? selected : [selected];
    const identities = new Set();
    for (const row of rows) {
        if (o.identityPath !== undefined) {
            const id = read(row, o.identityPath);
            if (!(typeof id === 'string' && id.trim() || typeof id === 'number' && Number.isFinite(id)))
                fail('OBSERVATION_ID_REQUIRED', 'Every observation needs a stable string or numeric identity.', 502);
            const key = `${typeof id}:${id}`;
            if (identities.has(key))
                fail('DUPLICATE_OBSERVATION', 'Observation identities must be unique within a returned batch.', 502);
            identities.add(key);
        }
        if (o.observedAtPath !== undefined) {
            const time = read(row, o.observedAtPath);
            if (typeof time !== 'string' || !/^\d{4}-\d{2}-\d{2}T.+(?:Z|[+-]\d{2}:\d{2})$/.test(time) || !Number.isFinite(Date.parse(time)))
                fail('INVALID_OBSERVATION_TIME', 'Observation times use ISO timestamps with an explicit timezone.', 502);
        }
        if (o.provenancePath !== undefined) {
            const provenance = read(row, o.provenancePath);
            if (!(typeof provenance === 'string' && provenance.trim() || provenance && typeof provenance === 'object' && !Array.isArray(provenance) && Object.keys(provenance).length))
                fail('OBSERVATION_PROVENANCE_REQUIRED', 'Every observation must include the declared provenance.', 502);
        }
    }
}
